### ISSUE TITLE
Add terminal colors in the base image without changing the aliases

### ISSUE THREAD

**Issue by PMax5** [swan-cern/jupyter-images#5]
https://github.com/swan-cern/jupyter-images/pull/2/files#diff-b093d34eec92adf6e0cc6e445edb7147ea45d25fb0c98f2f84a60f5aae6f34f7R70

**Comment by etejedor** [comment]
The referenced link shows an option to give colors to the prompt itself (machine and username), not to the result of `ls`. The decision is to leave that setting of the prompt as is (even though it is sterile in the case of Alma9), and keep the alias ls --color to have ls colors.
